// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: clamav.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthCheckRequest is an empty request for health checking.
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_clamav_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clamav_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_clamav_proto_rawDescGZIP(), []int{0}
}

// HealthCheckResponse contains the health status.
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_clamav_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clamav_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_clamav_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ScanFileRequest contains file data for a unary scan.
type ScanFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanFileRequest) Reset() {
	*x = ScanFileRequest{}
	mi := &file_clamav_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanFileRequest) ProtoMessage() {}

func (x *ScanFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clamav_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanFileRequest.ProtoReflect.Descriptor instead.
func (*ScanFileRequest) Descriptor() ([]byte, []int) {
	return file_clamav_proto_rawDescGZIP(), []int{2}
}

func (x *ScanFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ScanFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// ScanStreamRequest contains a chunk of file data for streaming scans.
type ScanStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanStreamRequest) Reset() {
	*x = ScanStreamRequest{}
	mi := &file_clamav_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanStreamRequest) ProtoMessage() {}

func (x *ScanStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clamav_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanStreamRequest.ProtoReflect.Descriptor instead.
func (*ScanStreamRequest) Descriptor() ([]byte, []int) {
	return file_clamav_proto_rawDescGZIP(), []int{3}
}

func (x *ScanStreamRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ScanStreamRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ScanStreamRequest) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// ScanResponse contains the scan result.
type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ScanTime      float64                `protobuf:"fixed64,3,opt,name=scan_time,json=scanTime,proto3" json:"scan_time,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_clamav_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clamav_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_clamav_proto_rawDescGZIP(), []int{4}
}

func (x *ScanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScanResponse) GetScanTime() float64 {
	if x != nil {
		return x.ScanTime
	}
	return 0
}

func (x *ScanResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_clamav_proto protoreflect.FileDescriptor

const file_clamav_proto_rawDesc = "" +
	"\n" +
	"\fclamav.proto\x12\x06clamav\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x0fScanFileRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"^\n" +
	"\x11ScanStreamRequest\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\"y\n" +
	"\fScanResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tscan_time\x18\x03 \x01(\x01R\bscanTime\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename2\x98\x02\n" +
	"\rClamAVScanner\x12F\n" +
	"\vHealthCheck\x12\x1a.clamav.HealthCheckRequest\x1a\x1b.clamav.HealthCheckResponse\x129\n" +
	"\bScanFile\x12\x17.clamav.ScanFileRequest\x1a\x14.clamav.ScanResponse\x12?\n" +
	"\n" +
	"ScanStream\x12\x19.clamav.ScanStreamRequest\x1a\x14.clamav.ScanResponse(\x01\x12C\n" +
	"\fScanMultiple\x12\x19.clamav.ScanStreamRequest\x1a\x14.clamav.ScanResponse(\x010\x01B8Z6github.com/DevHatRo/clamav-api-sdk-go/grpc/proto;protob\x06proto3"

var (
	file_clamav_proto_rawDescOnce sync.Once
	file_clamav_proto_rawDescData []byte
)

func file_clamav_proto_rawDescGZIP() []byte {
	file_clamav_proto_rawDescOnce.Do(func() {
		file_clamav_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clamav_proto_rawDesc), len(file_clamav_proto_rawDesc)))
	})
	return file_clamav_proto_rawDescData
}

var file_clamav_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_clamav_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),  // 0: clamav.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 1: clamav.HealthCheckResponse
	(*ScanFileRequest)(nil),     // 2: clamav.ScanFileRequest
	(*ScanStreamRequest)(nil),   // 3: clamav.ScanStreamRequest
	(*ScanResponse)(nil),        // 4: clamav.ScanResponse
}
var file_clamav_proto_depIdxs = []int32{
	0, // 0: clamav.ClamAVScanner.HealthCheck:input_type -> clamav.HealthCheckRequest
	2, // 1: clamav.ClamAVScanner.ScanFile:input_type -> clamav.ScanFileRequest
	3, // 2: clamav.ClamAVScanner.ScanStream:input_type -> clamav.ScanStreamRequest
	3, // 3: clamav.ClamAVScanner.ScanMultiple:input_type -> clamav.ScanStreamRequest
	1, // 4: clamav.ClamAVScanner.HealthCheck:output_type -> clamav.HealthCheckResponse
	4, // 5: clamav.ClamAVScanner.ScanFile:output_type -> clamav.ScanResponse
	4, // 6: clamav.ClamAVScanner.ScanStream:output_type -> clamav.ScanResponse
	4, // 7: clamav.ClamAVScanner.ScanMultiple:output_type -> clamav.ScanResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clamav_proto_init() }
func file_clamav_proto_init() {
	if File_clamav_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clamav_proto_rawDesc), len(file_clamav_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clamav_proto_goTypes,
		DependencyIndexes: file_clamav_proto_depIdxs,
		MessageInfos:      file_clamav_proto_msgTypes,
	}.Build()
	File_clamav_proto = out.File
	file_clamav_proto_goTypes = nil
	file_clamav_proto_depIdxs = nil
}
