// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: clamav.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClamAVScanner_HealthCheck_FullMethodName  = "/clamav.ClamAVScanner/HealthCheck"
	ClamAVScanner_ScanFile_FullMethodName     = "/clamav.ClamAVScanner/ScanFile"
	ClamAVScanner_ScanStream_FullMethodName   = "/clamav.ClamAVScanner/ScanStream"
	ClamAVScanner_ScanMultiple_FullMethodName = "/clamav.ClamAVScanner/ScanMultiple"
)

// ClamAVScannerClient is the client API for ClamAVScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClamAVScanner is the gRPC scanning service.
type ClamAVScannerClient interface {
	// HealthCheck checks the ClamAV service health.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// ScanFile scans a file with a unary request.
	ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	// ScanStream scans with client streaming (for large files).
	ScanStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ScanStreamRequest, ScanResponse], error)
	// ScanMultiple scans with bidirectional streaming (for multiple files).
	ScanMultiple(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ScanStreamRequest, ScanResponse], error)
}

type clamAVScannerClient struct {
	cc grpc.ClientConnInterface
}

func NewClamAVScannerClient(cc grpc.ClientConnInterface) ClamAVScannerClient {
	return &clamAVScannerClient{cc}
}

func (c *clamAVScannerClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ClamAVScanner_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clamAVScannerClient) ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, ClamAVScanner_ScanFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clamAVScannerClient) ScanStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ScanStreamRequest, ScanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClamAVScanner_ServiceDesc.Streams[0], ClamAVScanner_ScanStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanStreamRequest, ScanResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClamAVScanner_ScanStreamClient = grpc.ClientStreamingClient[ScanStreamRequest, ScanResponse]

func (c *clamAVScannerClient) ScanMultiple(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ScanStreamRequest, ScanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClamAVScanner_ServiceDesc.Streams[1], ClamAVScanner_ScanMultiple_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanStreamRequest, ScanResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClamAVScanner_ScanMultipleClient = grpc.BidiStreamingClient[ScanStreamRequest, ScanResponse]

// ClamAVScannerServer is the server API for ClamAVScanner service.
// All implementations must embed UnimplementedClamAVScannerServer
// for forward compatibility.
//
// ClamAVScanner is the gRPC scanning service.
type ClamAVScannerServer interface {
	// HealthCheck checks the ClamAV service health.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// ScanFile scans a file with a unary request.
	ScanFile(context.Context, *ScanFileRequest) (*ScanResponse, error)
	// ScanStream scans with client streaming (for large files).
	ScanStream(grpc.ClientStreamingServer[ScanStreamRequest, ScanResponse]) error
	// ScanMultiple scans with bidirectional streaming (for multiple files).
	ScanMultiple(grpc.BidiStreamingServer[ScanStreamRequest, ScanResponse]) error
	mustEmbedUnimplementedClamAVScannerServer()
}

// UnimplementedClamAVScannerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClamAVScannerServer struct{}

func (UnimplementedClamAVScannerServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedClamAVScannerServer) ScanFile(context.Context, *ScanFileRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanFile not implemented")
}
func (UnimplementedClamAVScannerServer) ScanStream(grpc.ClientStreamingServer[ScanStreamRequest, ScanResponse]) error {
	return status.Error(codes.Unimplemented, "method ScanStream not implemented")
}
func (UnimplementedClamAVScannerServer) ScanMultiple(grpc.BidiStreamingServer[ScanStreamRequest, ScanResponse]) error {
	return status.Error(codes.Unimplemented, "method ScanMultiple not implemented")
}
func (UnimplementedClamAVScannerServer) mustEmbedUnimplementedClamAVScannerServer() {}
func (UnimplementedClamAVScannerServer) testEmbeddedByValue()                       {}

// UnsafeClamAVScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClamAVScannerServer will
// result in compilation errors.
type UnsafeClamAVScannerServer interface {
	mustEmbedUnimplementedClamAVScannerServer()
}

func RegisterClamAVScannerServer(s grpc.ServiceRegistrar, srv ClamAVScannerServer) {
	// If the following call panics, it indicates UnimplementedClamAVScannerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClamAVScanner_ServiceDesc, srv)
}

func _ClamAVScanner_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClamAVScannerServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClamAVScanner_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClamAVScannerServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClamAVScanner_ScanFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClamAVScannerServer).ScanFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClamAVScanner_ScanFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClamAVScannerServer).ScanFile(ctx, req.(*ScanFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClamAVScanner_ScanStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClamAVScannerServer).ScanStream(&grpc.GenericServerStream[ScanStreamRequest, ScanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClamAVScanner_ScanStreamServer = grpc.ClientStreamingServer[ScanStreamRequest, ScanResponse]

func _ClamAVScanner_ScanMultiple_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClamAVScannerServer).ScanMultiple(&grpc.GenericServerStream[ScanStreamRequest, ScanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClamAVScanner_ScanMultipleServer = grpc.BidiStreamingServer[ScanStreamRequest, ScanResponse]

// ClamAVScanner_ServiceDesc is the grpc.ServiceDesc for ClamAVScanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClamAVScanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clamav.ClamAVScanner",
	HandlerType: (*ClamAVScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _ClamAVScanner_HealthCheck_Handler,
		},
		{
			MethodName: "ScanFile",
			Handler:    _ClamAVScanner_ScanFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ScanStream",
			Handler:       _ClamAVScanner_ScanStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ScanMultiple",
			Handler:       _ClamAVScanner_ScanMultiple_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "clamav.proto",
}
